config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "search", to: 'searches#index'
  resources :channel_statistic_groups do
    resources :escalation_levels, module: :channel_statistic_groups
  end
  resources :notification_groups
  resources :escalation_levels, except: [:new, :create]
  resources :hosts do
    member do
      get :ping
    end
    resources :software_interfaces, module: :hosts
  end
  resources :software_groups do
    resources :hosts, module: :software_groups
    resources :software, module: :software_groups
  end
  resources :software_connections do
    collection do
      get :search
    end
  end
  resources :interface_connectors do
    resources :software_connections, only: %i[index update], module: :interface_connectors
  end
  resources :software_interfaces do
    resources :interface_connectors, module: :software_interfaces
  end
  resources :software do
    resources :software_interfaces, module: :software
  end
  resources :locations do
    resources :hosts, module: :locations
  end
  resources :alerts, only: %i[index show]
  resources :channel_counters, only: [:index]
  resources :channel_statistics, only: %i[show index] do
    member do
      get :last_week
      get :last_month
      get :today
      get :current
      get :current_sent
    end
    collection do
      delete :delete_outdated
      get :queued
      get :problems
    end
    resources :alerts, only: %i[index show], module: :channel_statistics
    resources :notes, module: :channel_statistics
    resources :escalation_levels, module: :channel_statistics
  end
  resources :channels, only: %i[index show destroy] do
    resources :alerts, only: %i[index show], module: :channels
    resources :notes, module: :channels
    collection do
      delete :delete_outdated
    end
  end
  resources :servers do
    collection do
      get :sindex
    end
    member do
      get :ping
      get :doku
      post :update_properties
    end
    resources :server_configurations, only: %i[index show new create destroy]
    resources :alerts, only: %i[index show], module: :servers
    resources :notes, module: :servers
    resources :channels, only: %i[index destroy], module: :servers do
      collection do
        post :fetch_all
      end
      resources :alerts, only: %i[index show], module: :channels
    end
    resources :channel_statistics, only: %i[index show], module: :servers do
      collection do
        post :fetch_all
      end
    end
  end
  get 'home/index'

  get '/pages/index', to: 'pages#index'
  get '/pages/*page', to: 'pages#show', as: :page, format: false

  root to: 'home#index'
  mount Wobauth::Engine, at: '/auth'
  authenticate :user, ->(user) { user.is_admin? } do
    mount GoodJob::Engine => "good_job"
  end

end

app/models/server.rb
require 'uri'

# rubocop:todo Rails/UniqueValidationWithoutIndex
class Server < ApplicationRecord
  include ServerConcerns
  include EscalationStatusConcerns
  include NotableConcerns
  include Mirco::Condition

  # -- associations
  # belongs_to :location
  belongs_to :host, optional: true
  has_many :alerts, dependent: :destroy
  has_many :software_connections, dependent: :destroy
  has_many :all_notes, class_name: 'Note', dependent: :destroy, inverse_of: :server
  has_many :channels, dependent: :restrict_with_error
  has_many :channel_statistics, dependent: :restrict_with_error
  has_many :channel_counters, dependent: :destroy
  has_many :server_configurations, dependent: :restrict_with_error
  has_many :escalation_levels, as: :escalatable, dependent: :destroy

  # -- configuration
  has_encrypted :api_password
  store_accessor :properties, :server_uid
  store_accessor :properties, :server_jvm
  store_accessor :properties, :server_version
  store_accessor :properties, :server_settings
  store_accessor :properties, :system_info

  # -- validations and callbacks
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :uid, uniqueness: { case_sensitive: false, allow_blank: true }
  before_save :update_condition

  alias_attribute :to_s, :name
  alias_attribute :fullname, :name

  delegate :location, :hostname, :ipaddress, :up?, to: :host, allow_nil: true

  def uri
    URI(api_url)
  end

  def to_label
    "#{name} / #{host.name} (#{host.ipaddress}) / #{location.lid}"
  end

 def escalatable_attributes
    %w[ last_check last_check_ok ]
  end

  def update_condition
    if disabled
      set_condition(Mirco::States::NOTHING,
                    "Server is disabled")
    elsif manual_update
      set_condition(Mirco::States::NOTHING,
                    "Manual update enabled")
    elsif host.present? and !up?
      set_condition(Mirco::States::CRITICAL,
                    I18n.t(Mirco::States::CRITICAL, scope: 'mirco.condition') +
                    " Server unreachable, ping failed")
    else
      if escalation_status.state <= Mirco::States::OK
        set_condition(Mirco::States::OK,
                      I18n.t(Mirco::States::OK, scope: 'mirco.condition'))
      else
        set_condition(escalation_status.state,
                      escalation_status.message)
      end
    end
  end

end
# rubocop:enable Rails/UniqueValidationWithoutIndex

app/models/software_connection.rb
class SoftwareConnection < ApplicationRecord
  include SoftwareConnectionConcerns
  # -- associations
  belongs_to :location
  belongs_to :server
  belongs_to :source_connector, -> { where(type: 'TxConnector') },
             class_name: "InterfaceConnector", optional: true
  belongs_to :destination_connector, -> { where(type: 'RxConnector') },
             class_name: "InterfaceConnector", optional: true

  # -- configuration
  has_rich_text :description

  # -- validations and callbacks
  validates :source_url, :destination_url, :location_id, presence: true
  validates :source_url, uniqueness: { scope: [:location_id, :destination_url] }

  def to_s
    "#{location&.lid}: #{source_connector} \u27A0 #{destination_connector}"
  end

  def channel_ids
    (self[:channel_ids].present?) ? self[:channel_ids] : []
  end

end

app/controllers/interface_connectors/software_connections_controller.rb
class InterfaceConnectors::SoftwareConnectionsController < SoftwareConnectionsController
  before_action :set_interface_connector

  private

  def set_interface_connector
    @interface_connector = InterfaceConnector.find(params[:interface_connector_id])
  end

  def add_breadcrumb_show
    add_breadcrumb_for([set_interface_connector, @software_connection])
  end

  def location
    polymorphic_path(@interface_connector)
  end
end

app/controllers/software_connections_controller.rb
class SoftwareConnectionsController < ApplicationController
  before_action :set_software_connection, only: [:show, :edit, :update, :destroy]
  skip_before_action :add_breadcrumb_index

  # GET /software_connections
  def index
    if @interface_connector
      @software_connections = @interface_connector.software_connections
    else
      @software_connections = SoftwareConnection.all
    end
     @software_connections = @software_connections.includes(:location, :server, :source_connector, :destination_connector)
    if search_params.any?
      @software_connections = Connections::Query.new(@software_connections, search_params).all
    end
    @search = search_params || {}
    if @software_connections.empty?
      flash[:notice] = 'No matching results found, please try again'
      render 'search', formats: [:html]
    else
      respond_with(@software_connections) do |format|
        format.html do
          add_breadcrumb_index
        end
        format.puml do
          render format: :puml, layout: false
        end
        format.svg do
          diagram = Mirco::ConnectionsDiagram.new(@software_connections)
          send_file diagram.image(:svg), filename: "connections.svg",
                                         disposition: 'inline',
                                         type: 'image/svg+xml'
        end

      end
    end
  end

  def search
    @search = search_params || {}
  end

  # GET /software_connections/1
  def show
    respond_with(@software_connection) do |format|
      format.html do
        add_breadcrumb_show
      end
      format.puml do
        render format: :puml, layout: false
      end
      format.svg do
        diagram = Mirco::ConnectionDiagram.new(@software_connection)
        send_file diagram.image(:svg), filename: "connection-#{@software_connection.id}.svg",
                                       disposition: 'inline',
                                       type: 'image/svg+xml'
      end

    end
  end

  # GET /software_connections/new
  def new
    @software_connection = SoftwareConnection.new
    respond_with(@software_connection)
  end

  # GET /software_connections/1/edit
  def edit
  end

  # POST /software_connections
  def create
    @software_connection = SoftwareConnection.new(software_connection_params)

    @software_connection.save
    respond_with(@software_connection, location: location)
  end

  # PATCH/PUT /software_connections/1
  def update
    @software_connection.update(software_connection_params)
    respond_with(@software_connection, location: location)
  end

  # DELETE /software_connections/1
  def destroy
    @software_connection.destroy
    respond_with(@software_connection, location: location)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software_connection
      @software_connection = SoftwareConnection.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def software_connection_params
      params.require(:software_connection).permit(
        :location_id, :server_id,
        :source_connector_id, :source_url, 
        :destination_connector_id, :destination_url, 
        :ignore, :ignore_reason, :description
      )
    end

    def search_params
      searchparms = params.permit(*submit_parms, *non_search_params,
        :source_url, :destination_url, :source_connector_id, :destination_connector_id,
        :location_id, :ignore, :ignore_reason, :description, :channel_id,
        :disabled_channels,
        :id, :limit, :missing_connector).to_h
      searchparms.reject do |k, v|
        v.blank? || submit_parms.include?(k) || non_search_params.include?(k)
      end
   end

    def location
      polymorphic_path(@software_connection || :software_connections)
    end

    def submit_parms
      [ "utf8", "authenticity_token", "commit", "format", "view" ]
    end

    def non_search_params
      [ "interface_connector_id" ]
    end

end

app/helpers/software_connection_helper.rb
module SoftwareConnectionHelper
  def sw_connection_class(conn)
    if conn.ignore?
      "bg-ignore"
    elsif conn.disabled_channels?
      "bg-disabled"
    end
  end
end

app/views/software_connections/_form.html.erb
<%= simple_form_for(@software_connection) do |form| %>
<%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>

  <div class="alert alert-warning">
    <%= t('mirco.create_manual_software_connections_warning') %>
  </div>

  <div class="form-input">
    <%= form.association :location, wrapper: :horizontal_select,
          label_method: :to_s
       %>
    <%= form.association :server, wrapper: :horizontal_select,
          label_method: :to_s
       %>
    <%= form.association :source_connector, wrapper: :horizontal_select,
          label_method: :to_label
       %>
    <%= form.input :source_url
       %>
    <%= form.association :destination_connector, wrapper: :horizontal_select,
          label_method: :to_label
       %>
    <%= form.input :destination_url
       %>
    <%= form.input :ignore
       %>
    <%= form.input :ignore_reason
       %>
    <%= form.input :description, as: :rich_text_area
       %>

    <%= form.button :submit, class: 'btn btn-primary' %>
    <%= cancel_button %>
  </div>
<% end %>

app/views/software_connections/edit.html.erb
<%= render FormComponent.new(title: t('wobapphelpers.actions.edit', model: t('software_connection', scope: 'activerecord.models'))) do %>
  <%= render 'form' %>
<% end %>

app/views/software_connections/index.html.erb
<%= render 'shared/turbo-cache-control' %>

<h1><%= t('controller.software_connections') %></h1>

<div data-controller="datatables">
  <%= content_tag :table, role: :datatable,
        id: "software_connections_table",
        class: "table table-bordered table-responsive-xl",
        data: {
          'datatables-target': 'datatable',
          order: [[0, 'asc']].to_json
        } do %>
    <thead>
      <tr>
        <th><%= t('attributes.lid') %></th>
        <th><%= t('attributes.server') %></th>
        <th><%= t('attributes.software') %> (SRC)</th>
        <th><%= t('attributes.software_interface') %> (SRC)</th>
        <th><%= t('attributes.source_connector') %></th>
        <th><%= t('attributes.source_url') %></th>
        <th class="notvisible"><%= t('attributes.host') %></th>
        <th class="notvisible"><%= t('controller.channels') %></th>
        <th><%= t('attributes.software') %> (DST)</th>
        <th><%= t('attributes.software_interface') %> (DST)</th>
        <th><%= t('attributes.destination_connector') %></th>
        <th><%= t('attributes.destination_url') %></th>
        <th class="notvisible"><%= t('attributes.host') %></th>
        <th><%= t('attributes.ignore') %></th>
        <th class="notvisible"><%= t('attributes.ignore_reason') %></th>
        <th><%= t('attributes.description') %></th>
        <th class="text-center nosort"><%= t('mirco.action') %></th>
      </tr>
    </thead>
    <tfoot class="search">
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th class="nosearch"></th>
      </tr>
    </tfoot>
    <tbody>
      <% @software_connections.each do |software_connection| %>
        <%= content_tag(:tr, id: dom_id(software_connection), 
                             class: [dom_class(software_connection), sw_connection_class(software_connection)].join(" ")) do %>
          <td><%= software_connection.location.lid %></td>
          <td><%= software_connection.server %></td>
          <td><%= software_connection.source_connector&.sw_name %></td>
          <td><%= software_connection.source_connector&.if_name %></td>
          <td><%= software_connection.source_connector %></td>
          <td><%= software_connection.source_url %></td>
          <td><%= software_connection.src_url_host %></td>
          <td><%= Channel.where(id: software_connection.channel_ids)
                         .map(&:name).join('<br/>').html_safe
               %></td>
          <td><%= software_connection.destination_connector&.sw_name %></td>
          <td><%= software_connection.destination_connector&.if_name %></td>
          <td><%= software_connection.destination_connector %></td>
          <td><%= software_connection.destination_url %></td>
          <td><%= software_connection.dst_url_host %></td>
          <td><%= software_connection.ignore %></td>
          <td><%= software_connection.ignore_reason %></td>
          <td><%= software_connection.description %></td>
          <td class="text-center text-nowrap">
            <%= show_link software_connection %>
            <%= edit_link software_connection %>
            <%= delete_link software_connection %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
</div>

<br />

<%= back_link %>
<%= new_link SoftwareConnection %>

app/views/software_connections/index.puml.erb
@startuml
!theme mirco from <%= Rails.root.join('config') %>

<%= render Puml::MultipleConnectionsComponent.new(connections: @software_connections) %>

@enduml

app/views/software_connections/new.html.erb
<%= render FormComponent.new(title: t('wobapphelpers.actions.new', model: t('software_connection', scope: 'activerecord.models'))) do %>
  <%= render 'form' %>
<% end %>

app/views/software_connections/search.html.erb
<%= render 'shared/turbo-cache-control' %>

<div class="container">
  <%= form_tag(software_connections_path, method: :get, role: "form",
        class: 'form-horizontal card') do |f| %>

    <div class="card-header">
      <legend class="offset-sm-2 col-sm-10"><%= t('mirco.search_software_connections') %></legend>
    </div>
    <div class="card-body">

      <div class="mb-3 row location_id">
	<%= label_tag :location_id, t('attributes.location'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= select_tag "location_id",
                options_from_collection_for_select(Location.accessible_by(current_ability, :read), 'id', 'to_s', @search['location_id']),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row">
	<%= label_tag :source_url, t('attributes.source_url'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= text_field_tag "source_url", @search['source_url'], class: "form-control",
                placeholder: 'tcp://1.2.3.4:5678'

            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row">
	<%= label_tag :destination_url, t('attributes.destination_url'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= text_field_tag "destination_url", @search['destination_url'], class: "form-control",
                placeholder: 'tcp://1.2.3.4:5678'

            %>
          </select>
	</div>
      </div>


      <div class="mb-3 row">
	<%= label_tag :source_connector_id, t('attributes.source_connector'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= select_tag "source_connector_id",
                options_from_collection_for_select(
                  InterfaceConnector.accessible_by(current_ability, :read)
                                    .where(type: 'TxConnector'),
                  'id', 'to_label', @search['source_connector_id']),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row">
	<%= label_tag :destination_connector_id, t('attributes.destination_connector'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= select_tag "destination_connector_id",
                options_from_collection_for_select(
                  InterfaceConnector.accessible_by(current_ability, :read)
                                    .where(type: 'RxConnector'),
                  'id', 'to_label', @search['destination_connector_id']),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row">
	<%= label_tag :missing_connector, t('attributes.missing_connector'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= select_tag "missing_connector",
                options_for_select([:none, :both, :any, :source, :destination], 
                                   @search['missing_connector']),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row channel_id">
	<%= label_tag :channel_id, t('attributes.channel'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-10">
          <%= select_tag "channel_id",
                options_from_collection_for_select(Channel.accessible_by(current_ability, :read), 'id', 'fullname', @search['channel_id']),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>


      <div class="mb-3 row limit">
	<%= label_tag :limit, t('attributes.limit'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-3">
	  <%= text_field_tag :limit, (@search['limit'] || 100),  class: "form-control" %>
	</div>
      </div>

      <div class="mb-3 row">
	<%= label_tag :ignore, t('mirco.ignored_connections'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-3">
          <%= select_tag "ignore",
                options_for_select([:no, :yes], (@search['ignore'] || :no)),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row">
	<%= label_tag :disabled_channels, t('mirco.disabled_channels'), class: "col-sm-2 col-form-label" %>
	<div class="col-sm-3">
          <%= select_tag "disabled_channels",
                options_for_select([:no, :yes], (@search['disabled_channels'] || '')),
                include_blank: true,
                data: { controller: :select }
            %>
          </select>
	</div>
      </div>

      <div class="mb-3 row">
	<div class="col-sm-10 offset-sm-2">
	  <%= submit_tag(t('mirco.search_software_connections'),
                class: 'btn btn-primary') %>
          <%= button_tag(name: nil, method: :get,
                         class: "btn btn-secondary",
                         formaction: software_connections_path(format: :svg)) do %>
            <i class="fas fa-fw fa-project-diagram"></i>
          <% end %>
	  <%= cancel_button %>
	</div>
      </div>
    </div>
  <% end %>
</div>

app/views/software_connections/show.html.erb
<div class="card mb-2">
  <div class="card-header <%= sw_connection_class(@software_connection)  %>">
    <div class="d-flex w-250 justify-content-between">
      <div>
        <span class="subtitle">
          <%= t('activerecord.models.software_connection') %>:
          #<%= @software_connection.id %>
        </span>
        <h4 class="title"><%= @software_connection %></h4>
      </div>
      <div role="toolbar" class="pt-3">
        <%= edit_link(@software_connection) %>
        <%= delete_link(@software_connection) %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <div class="row">
      <div class="col-9">
        <table class="table table-borderless">

          <tr class=border-bottom>
            <th class="w-25 pe-3"><%= t('attributes.location')%>:</th>
            <td><%= link_to @software_connection.location, 
                            @software_connection.location,
                            class: 'primary-link'
                 %></td>
          </tr>

          <tr class=border-bottom>
            <th class="w-25 pe-3"><%= t('attributes.server')%>:</th>
            <td><%= link_to @software_connection.server, 
                            @software_connection.server,
                            class: 'primary-link'
                 %></td>
          </tr>

          <tr>
            <th>
              Source Connector
            </th>
            <td>
              <%= render Connections::ConnectorComponent.new(connector: @software_connection.source_connector) %>
            </td>
          </tr>
          <tr class="border-bottom">
            <th class="w-25 pe-3"><%= t('attributes.source_url')%>:</th>
            <td><%= @software_connection.source_url %> <br/>
                <%= @software_connection.src_url_host %>
            </td>
          </tr>

          <tr class="border-bottom">
            <th>
              Channels
            </th>
            <td>
              <%= @software_connection.channel_ids.map do |cid|
                    c = Channel.where(id: cid).first
                    if c.disabled?
                      %Q[<span class="bg-disabled">#{c.name}</span>]
                    else
                      %Q[<span class="">#{c.name}</span>]
                    end
                  end.join('<br/>').html_safe
               %>
            </td>
          </tr>

          <tr>
            <th>
              Destination Connector
            </th>
            <td>
              <%= render Connections::ConnectorComponent.new(connector: @software_connection.destination_connector) %>
            </td>
          </tr>

          <tr class="border-bottom">
            <th class="w-25 pe-3"><%= t('attributes.destination_url')%>:</th>
            <td><%= @software_connection.destination_url %> <br/>
                <%= @software_connection.dst_url_host %>
            </td>
          </tr>

          <tr>
            <th class="w-25 pe-3"><%= t('attributes.ignore')%>:</th>
            <td>
              <span class="<%= sw_connection_class(@software_connection) %>">
                <%= @software_connection.ignore %>
              </span>
           </td>
          </tr>

          <tr>
            <th class="w-25 pe-3"><%= t('attributes.ignore_reason')%>:</th>
            <td><%= @software_connection.ignore_reason %></td>
          </tr>

          <tr>
            <th class="w-25 pe-3"><%= t('attributes.description')%>:</th>
            <td><%= @software_connection.description %></td>
          </tr>
        </table>
      </div>
      <div class="col-3">
        <%= image_tag(software_connection_path(@software_connection, format: :svg)) %>
      </div>
    </div>
  </div>
</div>

<%= back_link %>
<%= new_link SoftwareConnection %>

app/views/software_connections/show.puml.erb
@startuml
!theme mirco from <%= Rails.root.join('config') %>

<%= render ConnectionPumlDefinitionsComponent.new(connection: @software_connection) %>
<%= render ConnectionPumlGraphsComponent.new(connection: @software_connection) %>

@enduml