config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "search", to: 'searches#index'
  resources :channel_statistic_groups do
    resources :escalation_levels, module: :channel_statistic_groups
  end
  resources :notification_groups
  resources :escalation_levels, except: [:new, :create]
  resources :hosts do
    member do
      get :ping
    end
    resources :software_interfaces, module: :hosts
  end
  resources :software_groups do
    resources :hosts, module: :software_groups
    resources :software, module: :software_groups
  end
  resources :software_connections do
    collection do
      get :search
    end
  end
  resources :interface_connectors do
    resources :software_connections, only: %i[index update], module: :interface_connectors
  end
  resources :software_interfaces do
    resources :interface_connectors, module: :software_interfaces
  end
  resources :software do
    resources :software_interfaces, module: :software
  end
  resources :locations do
    resources :hosts, module: :locations
  end
  resources :alerts, only: %i[index show]
  resources :channel_counters, only: [:index]
  resources :channel_statistics, only: %i[show index] do
    member do
      get :last_week
      get :last_month
      get :today
      get :current
      get :current_sent
    end
    collection do
      delete :delete_outdated
      get :queued
      get :problems
    end
    resources :alerts, only: %i[index show], module: :channel_statistics
    resources :notes, module: :channel_statistics
    resources :escalation_levels, module: :channel_statistics
  end
  resources :channels, only: %i[index show destroy] do
    resources :alerts, only: %i[index show], module: :channels
    resources :notes, module: :channels
    collection do
      delete :delete_outdated
    end
  end
  resources :servers do
    collection do
      get :sindex
    end
    member do
      get :ping
      get :doku
      post :update_properties
    end
    resources :server_configurations, only: %i[index show new create destroy]
    resources :alerts, only: %i[index show], module: :servers
    resources :notes, module: :servers
    resources :channels, only: %i[index destroy], module: :servers do
      collection do
        post :fetch_all
      end
      resources :alerts, only: %i[index show], module: :channels
    end
    resources :channel_statistics, only: %i[index show], module: :servers do
      collection do
        post :fetch_all
      end
    end
  end
  get 'home/index'

  get '/pages/index', to: 'pages#index'
  get '/pages/*page', to: 'pages#show', as: :page, format: false

  root to: 'home#index'
  mount Wobauth::Engine, at: '/auth'
  authenticate :user, ->(user) { user.is_admin? } do
    mount GoodJob::Engine => "good_job"
  end

end

app/models/home.rb
# frozen_string_literal: true

class Home
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @queued_messages = ChannelStatistic.active.current.queued.order('queued desc')
    @servers = Server.failed.order(:name).where(manual_update: false)
    @problems = ChannelStatistic.active.current.escalated.order('condition desc')
    @problems = @problems - @queued_messages
  end
end

app/views/home/_flash.html.erb
<div class="alert alert-warning alert-dismissible show noprint" role="alert">
  <span><%= alert_message %></span>
  <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/home/_index.html.erb
<div id="queued_messages">
  <%= content_tag :table, id: "queuing_table",
        class: "table table-bordered mb-0" do %>
    <thead>
      <tr class="search">
        <th class="text-start"><%= t('attributes.server') %></th>
        <th class="text-start"><%= t('attributes.channel') %></th>
        <th class="text-start"><%= t('attributes.destination') %></th>
        <th class="text-end d-none d-lg-table-cell"><%= t('attributes.received_last_30min') %></th>
        <th class="text-start"><%= t('attributes.last_message_received_at') %></th>
        <th class="text-end d-none d-lg-table-cell"><%= t('attributes.sent_last_30min') %></th>
        <th class="text-start"><%= t('attributes.last_message_sent_at') %></th>
        <th class="text-end"><%= t('attributes.queued') %></th>
        <th class="text-center"><%= t('attributes.updated_at') %></th>
        <th class="nosort text-center"><%= t('mirco.action') %></th>
      </tr>
    </thead>
    <tbody>
      <% queued_messages.each do |channel_statistic| %>
        <%= content_tag(:tr, id: dom_id(channel_statistic), class: dom_class(channel_statistic)) do %>
          <td class="text-start"><%= channel_statistic.server %></td>
          <td class="text-start">
            <%= link_to(
                  channel_statistic.channel,
                  channel_path(channel_statistic.channel),
                  class: "primary-link")
            %>
          </td>
          <td class="text-start"><%= channel_statistic.name %></td>
          <td class="text-end d-none d-lg-table-cell"><%= channel_statistic.received_last_30min %></td>
          <%= render TdEscalationComponent.new(
                escalatable: channel_statistic,
                attrib: 'last_message_received_at',
                manual_update: channel_statistic.server.manual_update
            ) %>

          <td class="text-end d-none d-lg-table-cell"><%= channel_statistic.sent_last_30min %></td>
          <%= render TdEscalationComponent.new(
                escalatable: channel_statistic,
                attrib: 'last_message_sent_at',
                manual_update: channel_statistic.server.manual_update
            ) %>

          <%= render TdEscalationComponent.new(
                escalatable: channel_statistic,
                attrib: 'queued',
                alert: (channel_statistic.sent_last_30min < 1),
                css: 'text-end',
                manual_update: channel_statistic.server.manual_update
              ) %>
          <%= render TdEscalationComponent.new(
                escalatable: channel_statistic,
                attrib: 'updated_at',
                manual_update: channel_statistic.server.manual_update
              ) %>
          <td class="text-nowrap text-center">
            <%= link_to(raw(%Q[<i class="fas fa-chart-bar"></i>]), channel_statistic, class: 'btn btn-secondary btn-sm my-0') %>

          </td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
</div>

app/views/home/_problem_states.html.erb
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::WARNING,
                  count: ChannelStatistic.active.current.warning.count,
                  link:  problems_channel_statistics_path(condition: Mirco::States::WARNING),
                  myframe: 'problems') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::CRITICAL,
                  count: ChannelStatistic.active.current.critical.count,
                  link:  problems_channel_statistics_path(condition: Mirco::States::CRITICAL),
                  myframe: 'problems') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::UNKNOWN,
                  count: ChannelStatistic.active.current.unknown.count,
                  link:  problems_channel_statistics_path(condition: Mirco::States::UNKNOWN),
                  myframe: 'problems') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::NOTHING,
                  count: ChannelStatistic.active.current.nothing.count,
                  link:  problems_channel_statistics_path(condition: Mirco::States::NOTHING),
                  myframe: 'problems') %>
</div>
<div class="me-2">
  <%= link_to problems_channel_statistics_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'problems' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= ChannelStatistic.active.current.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/_queued_states.html.erb
<div class="me-2">
  <%= link_to queued_channel_statistics_path(all: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'queued' do %>
    All queued messages
    <span class="badge text-bg-secondary">
      <%= ChannelStatistic.active.current.queued.count %>
    </span>
  <% end %>
</div>

<div class="me-2">
  <%= link_to queued_channel_statistics_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'queued' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= ChannelStatistic.active.current.queued.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/_server_states.html.erb
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::OK,
                  count: Server.active.ok.count,
                  link:  sindex_servers_path(condition: Mirco::States::OK),
                  myframe: 'servers') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::WARNING,
                  count: Server.active.warning.count,
                  link:  sindex_servers_path(condition: Mirco::States::WARNING),
                  myframe: 'servers') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::CRITICAL,
                  count: Server.active.critical.count,
                  link:  sindex_servers_path(condition: Mirco::States::CRITICAL),
                  myframe: 'servers') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::UNKNOWN,
                  count: Server.active.unknown.count,
                  link:  sindex_servers_path(condition: Mirco::States::UNKNOWN),
                  myframe: 'servers') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Mirco::States::NOTHING,
                  count: Server.active.nothing.count,
                  link:  sindex_servers_path(condition: Mirco::States::NOTHING),
                  myframe: 'servers') %>
</div>
<div class="me-2">
  <%= link_to sindex_servers_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'servers' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= Server.active.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/index.html.erb
<%= turbo_stream_from :home %>
<div class="container-xl">
  <div class="card mt-3">
    <div class="card-header">
      <div class="row">
        <div class="col-xs-5 col-md-4 col-ml-3">
          <h4 class="me-4 pt-1">Queued Messages</h4>
        </div>
        <div class="d-flex col-xs-7 col-md-8 col-ml-9">
          <%= render 'queued_states' %>
        </div>
      </div>
    </div>
    <div>
      <%= turbo_frame_tag("queued", src: queued_channel_statistics_path, refresh: "morph") %>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-header">
      <div class="row">
        <div class="col-xs-5 col-md-4 col-ml-3">
          <h4 class="me-4 pt-1">Potential Message Problems</h4>
        </div>
        <div class="d-flex col-xs-7 col-md-8 col-ml-9">
          <%= render 'problem_states' %>
          <% if current_user&.is_admin? %>
            <%= link_to icon_edit + " Escalation Levels", escalation_levels_path,
                class: 'btn btn-outline-secondary ms-auto' %>
          <% end %>
        </div>
      </div>
    </div>
    <div>
      <%= turbo_frame_tag("problems", src: problems_channel_statistics_path, refresh: "morph") %>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-header">
      <div class="row">
        <div class="col-xs-5 col-md-4 col-ml-3">
          <h4 class="me-4 pt-1">Server Status</h4>
        </div>
        <div class="d-flex col-xs-7 col-md-8 col-ml-9">
          <%= render 'server_states' %>
        </div>
      </div>
    </div>
    <div>
      <%= turbo_frame_tag("servers", src: sindex_servers_path, refresh: "morph") %>
    </div>
  </div>


</div>